name: CI Frontend Vue

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "main"
        
permissions:
  contents: write # repo write permission update

jobs:
  build-and-push-frontend-vue-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./frontend-vue
      run: npm install

    - name: Build Vue.js application
      working-directory: ./frontend-vue
      run: npm run build

    - name: Get current date and time
      id: datetime
      run: echo "DATE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV


    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # 프로젝트 루트를 기준으로 설정
        file: ./gitops/frontend-vue/Dockerfile  # Dockerfile의 위치를 정확히 지정      
        push: true
        tags: ${{ secrets.AZURE_URL }}/frontend-vue:${{ github.event.inputs.name }}-${{ env.DATE_TAG }}

    - name: Update Kustomize Deployment with New Tag
      run: |
        TAG="${{ github.event.inputs.name }}-${{ env.DATE_TAG }}"
        sed -i "s|newTag: .*$|newTag: $TAG|g" gitops/frontend-vue/overlays/dev/kustomization.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./gitops/frontend-vue/overlays/dev/kustomization.yaml
        git commit -m "Update frontend-vue-deployment.yaml with tag $TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
